# AI Exposure categories:
#   Enabler    — structurally necessary for AI infrastructure regardless of which application wins
#   Compounder — existing moat gets stronger because of AI
#   Disruptor  — building net-new value where AI is the product
#   Exposed    — core business threatened by AI substitution or commoditization
#   Neutral    — AI is a minor efficiency tool, not a thesis driver

AI_EXPOSURE = {
    # Semiconductors
    "TSM":  "Enabler",
    "UMC":  "Enabler",
    "NVDA": "Enabler",
    "AMD":  "Enabler",
    "AVGO": "Compounder",
    "MRVL": "Compounder",
    "MPWR": "Compounder",
    "ARM":  "Enabler",
    "MTSI": "Neutral",
    "SIMO": "Neutral",
    "RMBS": "Enabler",
    "SITM": "Enabler",
    "AMBA": "Enabler",
    "ASML": "Enabler",
    "LRCX": "Enabler",
    "KLAC": "Enabler",
    "AMAT": "Enabler",
    "ENTG": "Enabler",
    "MKSI": "Enabler",
    "ACLS": "Neutral",
    "UCTT": "Neutral",
    "ICHR": "Neutral",
    "COHU": "Neutral",
    "FORM": "Neutral",
    "ONTO": "Neutral",
    "NVMI": "Neutral",
    "CAMT": "Neutral",
    "TER":  "Neutral",
    "INTC": "Exposed",
    "MU":   "Enabler",
    "WDC":  "Neutral",
    "STX":  "Neutral",
    "SNPS": "Enabler",
    "CDNS": "Enabler",
    "KEYS": "Enabler",
    # Cloud
    "AMZN": "Enabler",
    "MSFT": "Compounder",
    "GOOGL":"Compounder",
    "ORCL": "Compounder",
    "ANET": "Enabler",
    "VRT":  "Enabler",
    # Enterprise SaaS
    "CRM":  "Compounder",
    "HUBS": "Compounder",
    "WDAY": "Exposed",
    "INTU": "Compounder",
    "NOW":  "Compounder",
    "ADBE": "Compounder",
    "TEAM": "Compounder",
    "SAP":  "Exposed",
    "PAYC": "Neutral",
    "PCTY": "Neutral",
    "NICE": "Compounder",
    "ADP":  "Neutral",
    "PAYX": "Neutral",
    "FIVN": "Exposed",
    "SSNC": "Neutral",
    "MANH": "Neutral",
    "GTLB": "Compounder",
    "PD":   "Neutral",
    # Enterprise AI
    "PLTR": "Disruptor",
    "SNOW": "Disruptor",
    "DDOG": "Compounder",
    "MDB":  "Compounder",
    "ZS":   "Compounder",
    # Cybersecurity
    "CRWD": "Compounder",
    "S":    "Compounder",
    "PANW": "Compounder",
    "FTNT": "Compounder",
    "CHKP": "Neutral",
    "OKTA": "Compounder",
    "SAIL": "Compounder",
    "QLYS": "Neutral",
    "VRNT": "Neutral",
    "TENB": "Compounder",
    "GEN":  "Neutral",
    "VRNS": "Compounder",
    "RPD":  "Neutral",
}
