# AI Exposure categories:
#   Enabler    — structurally necessary for AI infrastructure regardless of which application wins
#   Compounder — existing moat gets stronger because of AI
#   Disruptor  — building net-new value where AI is the product
#   Exposed    — core business threatened by AI substitution or commoditization
#   Neutral    — AI is a minor efficiency tool, not a thesis driver

AI_EXPOSURE = {
    # Semiconductors
    "TSM":  "Enabler",
    "UMC":  "Enabler",
    "NVDA": "Enabler",
    "AMD":  "Enabler",
    "QCOM": "Compounder",
    "AVGO": "Compounder",
    "MRVL": "Compounder",
    "MPWR": "Compounder",
    "MCHP": "Neutral",
    "QRVO": "Neutral",
    "SWKS": "Neutral",
    "ARM":  "Enabler",
    "SLAB": "Neutral",
    "ALGM": "Neutral",
    "MTSI": "Neutral",
    "CRUS": "Neutral",
    "SIMO": "Neutral",
    "MXL":  "Neutral",
    "RMBS": "Enabler",
    "SITM": "Enabler",
    "PI":   "Neutral",
    "AMBA": "Enabler",
    "ASML": "Enabler",
    "LRCX": "Enabler",
    "KLAC": "Enabler",
    "AMAT": "Enabler",
    "ENTG": "Enabler",
    "MKSI": "Enabler",
    "ACLS": "Neutral",
    "UCTT": "Neutral",
    "ICHR": "Neutral",
    "COHU": "Neutral",
    "FORM": "Neutral",
    "ONTO": "Neutral",
    "NVMI": "Neutral",
    "CAMT": "Neutral",
    "TER":  "Neutral",
    "INTC": "Exposed",
    "TXN":  "Neutral",
    "NXPI": "Compounder",
    "STM":  "Neutral",
    "ADI":  "Compounder",
    "ON":   "Compounder",
    "WOLF": "Neutral",
    "MU":   "Enabler",
    "WDC":  "Neutral",
    "STX":  "Neutral",
    "SNPS": "Enabler",
    "CDNS": "Enabler",
    "AVT":  "Neutral",
    "ARW":  "Neutral",
    "CDW":  "Neutral",
    "KEYS": "Enabler",
    # Cloud
    "AMZN": "Enabler",
    "MSFT": "Compounder",
    "GOOGL":"Compounder",
    "ORCL": "Compounder",
    "ESTC": "Compounder",
    "AKAM": "Neutral",
    "GDDY": "Neutral",
    "FFIV": "Neutral",
    "VRSN": "Neutral",
    "ANET": "Enabler",
    "FSLY": "Neutral",
    # Enterprise SaaS
    "CRM":  "Compounder",
    "HUBS": "Compounder",
    "WDAY": "Exposed",
    "INTU": "Compounder",
    "NOW":  "Compounder",
    "ADBE": "Compounder",
    "TEAM": "Compounder",
    "SAP":  "Exposed",
    "PAYC": "Neutral",
    "PCTY": "Neutral",
    "NICE": "Compounder",
    "ADP":  "Neutral",
    "PAYX": "Neutral",
    "FIVN": "Exposed",
    "SSNC": "Neutral",
    "MANH": "Neutral",
    "GTLB": "Compounder",
    "PD":   "Neutral",
    "VEEV": "Compounder",
    "IOT":  "Enabler",
    "ZM":   "Exposed",
    "DBX":  "Neutral",
    "BOX":  "Exposed",
    "PTC":  "Compounder",
    "TYL":  "Neutral",
    "ADSK": "Compounder",
    "JKHY": "Neutral",
    "BR":   "Neutral",
    "TRMB": "Compounder",
    "MSI":  "Compounder",
    "PCOR": "Neutral",
    "NCNO": "Neutral",
    "SHOP": "Compounder",
    "MSCI": "Compounder",
    # Data Analytics
    "FICO": "Compounder",
    "VRSK": "Compounder",
    "SPGI": "Compounder",
    "MCO":  "Compounder",
    "CSGP": "Compounder",
    # IT Services
    "ACN":  "Compounder",
    "CTSH": "Exposed",
    # Ad Platform
    "APP":  "Disruptor",
    "TTD":  "Compounder",
    # Payment Network
    "V":    "Neutral",
    "MA":   "Neutral",
    # Enterprise AI
    "PLTR": "Disruptor",
    "SNOW": "Disruptor",
    "DDOG": "Compounder",
    "MDB":  "Compounder",
    "ZS":   "Compounder",
    # Cybersecurity
    "CRWD": "Compounder",
    "S":    "Compounder",
    "PANW": "Compounder",
    "FTNT": "Compounder",
    "CHKP": "Neutral",
    "OKTA": "Compounder",
    "SAIL": "Compounder",
    "QLYS": "Neutral",
    "VRNT": "Neutral",
    "TENB": "Compounder",
    "GEN":  "Neutral",
    "VRNS": "Compounder",
    "RPD":  "Neutral",
}
